#!/usr/bin/env python3
"""Memory-backed v19.11.4.1 LBA4 writer probe for the authentic SanDisk gold.

The probe never opens a real device.  ``CreateFileA``/``ReadFile``/``WriteFile``
are intercepted and backed by an in-memory bytearray.  Only two CRT formatting
helpers are stubbed; the historical ``fcn.10006090`` LBA4 builder itself,
including its full rolling loop and the post-XOR flag stores, executes as the
official x86 machine code.

The experiment is intentionally stronger than checking the two flag bytes: it
requires the official writer to reproduce all 512 bytes of the checked-in
authentic no-password SanDisk LBA4 exactly.  The caller-owned backing is first
converted to the writer's pre-rolling representation; the 0x2F restore node is
the official reader view with only bDataToServer/bConnetServer set to their
producer-side zero values.  HSerial and the non-mirrored second onlyid are kept
unchanged.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import struct
import sys
from pathlib import Path

V19_DLL_SHA256 = "584e591dc679a2dad2c6d15b4ea96f8be39ae40e7841e883ea9cbc2f35a89814"
AUTHENTIC_GOLD_SHA256 = "d6a935525b9e7bba9926a5ee1e2a74996d2aaf93bc6291723eaaedcff679a258"
AUTHENTIC_LBA4_SHA256 = "c26628566108031f439f999a46858476414ec8e7d1030a8293c9df0c463ad5d8"
ONLYID = 794_661_040
WRITER_RVA = 0x06090
WRITER_END_RVA = 0x062F4


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def require_file_hash(path: Path, expected: str) -> bytes:
    data = path.read_bytes()
    actual = sha256(data)
    if actual != expected:
        raise SystemExit(f"SHA-256 mismatch for {path}: expected {expected}, got {actual}")
    return data


def rolling(data: bytes, onlyid: int) -> bytes:
    """Protocol rolling transform used only to prepare caller-owned backing."""
    out = bytearray(data)
    key = ((onlyid & 0xFFFF) ^ (onlyid >> 16)) & 0xFFFF
    for index in range(0xF4):
        offset = index * 2
        word = struct.unpack_from("<H", out, offset)[0] ^ key
        struct.pack_into("<H", out, offset, word)
        key = (key + 0x100 - index - 1) & 0xFFFF
    return bytes(out)


def parse_args() -> argparse.Namespace:
    home = Path.home()
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--dll",
        type=Path,
        default=Path("/private/tmp/cemsusbregsiter_19.11.4.1.dll"),
    )
    parser.add_argument(
        "--framework-dir",
        type=Path,
        default=home / "Desktop/u_disk/analyze/scripts",
        help="directory containing emu_framework.py",
    )
    parser.add_argument(
        "--image",
        type=Path,
        default=Path(
            "audit/protocol/gold/authentic-nopwd/sandisk_ultra_20260823_lba0_12.bin"
        ),
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    require_file_hash(args.dll, V19_DLL_SHA256)
    image = require_file_hash(args.image, AUTHENTIC_GOLD_SHA256)
    if len(image) != 13 * 512:
        raise SystemExit(f"expected 6656-byte LBA0-LBA12 image, got {len(image)} bytes")

    target = image[4 * 512 : 5 * 512]
    if sha256(target) != AUTHENTIC_LBA4_SHA256:
        raise SystemExit("authentic SanDisk LBA4 hash changed")
    if target[0x45:0x47] != b"\x00\x00":
        raise SystemExit("authentic SanDisk physical flag bytes changed")
    if not any(target[0x47:0x1FC]):
        raise SystemExit("probe unexpectedly lost the non-zero backing profile")

    # ReadSector4's rolling view is the correct pre-rolling representation for
    # caller-owned backing.  It also exposes D4/D9 at the two post-XOR writer
    # exception bytes; replace only those two node bytes with the producer-side
    # values being tested here (00/00).
    reader = rolling(target[0x18:], ONLYID)
    if reader[0x2D:0x2F] != bytes.fromhex("d4d9"):
        raise SystemExit("authentic SanDisk reader-view flags changed")
    node = bytearray(reader[:0x2F])
    node[0x2D:0x2F] = b"\x00\x00"

    seed_sector = bytearray(target)
    seed_sector[0x18:] = reader
    seed = bytearray(0x3000)
    seed[4 * 512 : 5 * 512] = seed_sector
    seed[5 * 512 : 13 * 512] = image[5 * 512 : 13 * 512]

    sys.path.insert(0, str(args.framework_dir))
    try:
        from emu_framework import EmuFramework, _parse_iat  # type: ignore
        from unicorn import UC_HOOK_CODE
        from unicorn.x86_const import UC_X86_REG_EAX, UC_X86_REG_EIP, UC_X86_REG_ESP
    except ImportError as exc:
        raise SystemExit(f"analysis dependency unavailable: {exc}") from exc

    emu = EmuFramework(str(args.dll), stack_size=0x500000)
    runtime_stubs: list[str] = []

    # These two functions format the PhysicalDrive path / debug message only.
    # Stubbing them avoids requiring DllMain to initialize the bundled MSVC CRT;
    # no protocol bytes are generated by either helper.
    def sprintf_stub(e, esp: int) -> int:
        runtime_stubs.append("sprintf-path")
        dest = e.read_dword(esp + 4)
        drive = e.read_dword(esp + 12)
        value = (r"\\.\PHYSICALDRIVE" + str(drive)).encode("ascii")
        e.mem_write(dest, value + bytes([0]))
        return len(value)

    def debug_format_stub(e, esp: int) -> int:
        runtime_stubs.append("debug-format")
        dest = e.read_dword(esp + 4)
        value = b"writer-ok"
        e.mem_write(dest, value + bytes([0]))
        return len(value)

    emu.stub_function(0x0F060, sprintf_stub)
    emu.stub_function(0x0F0A0, debug_format_stub)

    files: dict[int, dict[str, object]] = {}
    next_fd = [1000]
    write_calls: list[tuple[int, bytes]] = []
    iat_calls: list[str] = []

    def stdcall_return(e, esp: int, value: int, argc: int) -> None:
        return_address = e.read_dword(esp)
        e.uc.reg_write(UC_X86_REG_EAX, value & 0xFFFFFFFF)
        e.uc.reg_write(UC_X86_REG_EIP, return_address)
        e.uc.reg_write(UC_X86_REG_ESP, esp + 4 + argc * 4)

    def iat_handler(name: str):
        def handler(e, esp: int) -> None:
            iat_calls.append(name)
            if name == "CreateFileA":
                fd = next_fd[0]
                next_fd[0] += 1
                path = e.read_str(e.read_dword(esp + 4)).decode("ascii")
                access = e.read_dword(esp + 8)
                if path != r"\\.\PHYSICALDRIVE4":
                    raise RuntimeError(f"unexpected virtual path {path!r}")
                files[fd] = {"data": seed.copy(), "pos": 0, "access": access}
                stdcall_return(e, esp, fd, 7)
                return
            if name == "GetLastError":
                stdcall_return(e, esp, 0, 0)
                return
            if name == "SetFilePointer":
                fd = e.read_dword(esp + 4)
                distance = e.read_dword(esp + 8)
                method = e.read_dword(esp + 16)
                file = files[fd]
                pos = int(file["pos"])
                data = file["data"]
                assert isinstance(data, bytearray)
                if method == 0:
                    pos = distance
                elif method == 1:
                    pos += distance
                elif method == 2:
                    pos = len(data) + distance
                else:
                    raise RuntimeError(f"unexpected SetFilePointer method {method}")
                file["pos"] = pos
                stdcall_return(e, esp, pos, 4)
                return
            if name == "ReadFile":
                fd = e.read_dword(esp + 4)
                dest = e.read_dword(esp + 8)
                size = e.read_dword(esp + 12)
                count_ptr = e.read_dword(esp + 16)
                file = files[fd]
                data = file["data"]
                assert isinstance(data, bytearray)
                pos = int(file["pos"])
                chunk = bytes(data[pos : pos + size])
                e.mem_write(dest, chunk + bytes(size - len(chunk)))
                file["pos"] = pos + len(chunk)
                if count_ptr:
                    e.mem_write(count_ptr, struct.pack("<I", len(chunk)))
                stdcall_return(e, esp, 1, 5)
                return
            if name == "WriteFile":
                fd = e.read_dword(esp + 4)
                source = e.read_dword(esp + 8)
                size = e.read_dword(esp + 12)
                count_ptr = e.read_dword(esp + 16)
                file = files[fd]
                data = file["data"]
                assert isinstance(data, bytearray)
                pos = int(file["pos"])
                chunk = bytes(e.mem_read(source, size))
                data[pos : pos + size] = chunk
                file["pos"] = pos + size
                write_calls.append((pos, chunk))
                if count_ptr:
                    e.mem_write(count_ptr, struct.pack("<I", size))
                stdcall_return(e, esp, 1, 5)
                return
            if name == "OutputDebugStringA":
                stdcall_return(e, esp, 0, 1)
                return
            if name == "CloseHandle":
                stdcall_return(e, esp, 1, 1)
                return
            raise RuntimeError(f"unexpected IAT handler {name}")

        return handler

    needed = {
        "CreateFileA",
        "GetLastError",
        "SetFilePointer",
        "ReadFile",
        "WriteFile",
        "OutputDebugStringA",
        "CloseHandle",
    }
    installed: set[str] = set()
    cache: dict[int, int] = {}
    for iat_rva, (_dll_name, function_name) in _parse_iat(emu.dll, emu.image_base).items():
        if function_name in needed:
            emu.patch_iat(iat_rva, iat_handler(function_name), cache)
            installed.add(function_name)
    if installed != needed:
        raise SystemExit(f"required IAT boundary missing: {sorted(needed - installed)}")

    executed: list[int] = []
    start = emu.image_base + WRITER_RVA
    end = emu.image_base + WRITER_END_RVA - 1

    def core_hook(_uc, address: int, _size: int, _user_data) -> None:
        executed.append(address - emu.image_base)

    emu.uc.hook_add(UC_HOOK_CODE, core_hook, begin=start, end=end)

    obj = emu.alloc(0x1100)
    emu.mem_write(obj, bytes(0x1100))
    emu.mem_write(obj + 0x1008, struct.pack("<I", 512))
    node_ptr = emu.alloc(0x2F)
    emu.mem_write(node_ptr, bytes(node))

    # The real caller reserves two additional stack DWORDs before pushing the
    # drive index and node pointer; fcn.10006090 returns with `ret 0x10`.
    ret = emu.call_thiscall(WRITER_RVA, obj, 4, node_ptr, 0, 0, timeout=8_000_000)
    matching_writes = [
        data for offset, data in write_calls if offset == 4 * 512 and len(data) == 512
    ]
    output = matching_writes[-1] if matching_writes else b""
    differences = [
        index for index, (actual, expected) in enumerate(zip(output, target)) if actual != expected
    ]
    exceptions = [
        item
        for item in emu._trace_log
        if item.startswith("EXCEPTION") or item.startswith("UNMAPPED")
    ]

    result = {
        "dll_sha256": V19_DLL_SHA256,
        "gold_sha256": AUTHENTIC_GOLD_SHA256,
        "function": "CEMSUsbRegsiter.dll v19.11.4.1::fcn.10006090",
        "function_rva": f"0x{WRITER_RVA:05X}",
        "return": ret,
        "input_second_onlyid": f"0x{struct.unpack_from('<I', node, 4)[0]:08X}",
        "input_hserial": node[8:0x1C].hex(),
        "input_node_flags": node[0x2D:0x2F].hex(),
        "reader_flags": reader[0x2D:0x2F].hex(),
        "target_wire_flags": target[0x45:0x47].hex(),
        "output_wire_flags": output[0x45:0x47].hex() if output else None,
        "target_lba4_sha256": AUTHENTIC_LBA4_SHA256,
        "output_sha256": sha256(output) if output else None,
        "exact_512_match": output == target,
        "diff_count": len(differences) if output else 512,
        "diff_offsets": [f"0x{offset:03X}" for offset in differences[:40]],
        "write_calls": [
            {"offset": offset, "size": len(data)} for offset, data in write_calls
        ],
        "executed_core_first_rva": f"0x{min(executed):05X}" if executed else None,
        "executed_core_last_rva": f"0x{max(executed):05X}" if executed else None,
        "executed_core_instruction_count": len(executed),
        "runtime_stubs": runtime_stubs,
        "iat_calls": iat_calls,
        "emulator_exceptions": exceptions,
    }
    print(json.dumps(result, indent=2))

    if ret != 1:
        raise SystemExit("historical writer did not report success")
    if exceptions:
        raise SystemExit("emulator encountered an unexpected exception/unmapped access")
    if write_calls != [(4 * 512, target)]:
        raise SystemExit("historical writer did not issue exactly one exact LBA4 write")
    if output != target or sha256(output) != AUTHENTIC_LBA4_SHA256:
        raise SystemExit("historical writer did not reproduce authentic LBA4 exactly")


if __name__ == "__main__":
    main()
