use super::*;

pub(super) fn edpf96_fields(base: usize, index: usize, entry: &EdpfEntry96) -> Vec<SectorField> {
    let group = format!("Entry[{index}]");
    vec![
        grouped_field(
            base,
            base + 4,
            group.clone(),
            "EDPF magic",
            "EDPF",
            FieldStyle::Magic,
        ),
        grouped_field(
            base + 0x04,
            base + 0x08,
            group.clone(),
            "版本",
            format!("0x{:08X}", entry.version),
            FieldStyle::Flag,
        ),
        grouped_field(
            base + 0x08,
            base + 0x0c,
            group.clone(),
            "分区数量",
            entry.partition_count.to_string(),
            FieldStyle::Flag,
        ),
        grouped_field(
            base + 0x0c,
            base + 0x10,
            group.clone(),
            "类型",
            format!(
                "{} ({})",
                ptype_name(entry.partition_type),
                entry.partition_type
            ),
            FieldStyle::Flag,
        ),
        grouped_field(
            base + 0x10,
            base + 0x14,
            group.clone(),
            "NeedDisturb",
            entry.need_disturb.to_string(),
            FieldStyle::Flag,
        ),
        grouped_field(
            base + 0x14,
            base + 0x18,
            group.clone(),
            "NeedEncrypt",
            entry.need_encrypt.to_string(),
            FieldStyle::Flag,
        ),
        grouped_field(
            base + 0x18,
            base + 0x20,
            group.clone(),
            "起始 LBA",
            entry.start_sector.to_string(),
            FieldStyle::Address,
        ),
        grouped_field(
            base + 0x20,
            base + 0x28,
            group.clone(),
            "扇区字节",
            entry.sector_size.to_string(),
            FieldStyle::Size,
        ),
        grouped_field(
            base + 0x28,
            base + 0x30,
            group.clone(),
            "大小",
            format!(
                "{} B / {}",
                entry.partition_size,
                human_bytes(entry.partition_size)
            ),
            FieldStyle::Size,
        ),
        grouped_field(
            base + 0x30,
            base + 0x34,
            group.clone(),
            "UserKeyCRC",
            format!("0x{:08X}", entry.user_key_crc),
            FieldStyle::Checksum,
        ),
        grouped_field(
            base + 0x34,
            base + 0x38,
            group.clone(),
            "FileKeyCRC",
            format!("0x{:08X}", entry.file_key_crc),
            FieldStyle::Checksum,
        ),
        grouped_field(
            base + 0x38,
            base + 0x48,
            group.clone(),
            "加密 FileKey",
            hex_bytes(&entry.encrypted_file_key),
            FieldStyle::Identity,
        ),
        grouped_field(
            base + 0x48,
            base + 0x58,
            group.clone(),
            "兼容 Key",
            hex_bytes(&entry.compatibility_key),
            FieldStyle::Identity,
        ),
        grouped_field(
            base + 0x58,
            base + 0x59,
            group.clone(),
            "EncryptMode",
            entry.encrypt_mode.to_string(),
            FieldStyle::Flag,
        ),
        grouped_field(
            base + 0x59,
            base + 0x60,
            group,
            "保留字节",
            hex_bytes(&entry.reserved),
            FieldStyle::Flag,
        ),
    ]
}
