name: Future Compatibility

on:
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * 1"

permissions:
  contents: read

jobs:
  build_facts:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.build.outputs.compatibility }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Python tooling
        uses: ./.github/actions/setup-python-tooling
      - id: build
        run: uv run --locked python scripts/ci/build_config.py

  latest:
    name: ${{ matrix.label }} / latest stable Rust
    needs: build_facts
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.build_facts.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Python tooling
        uses: ./.github/actions/setup-python-tooling
      - name: Install latest stable Rust
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87
        with:
          toolchain: stable
          components: clippy
      - name: Test all targets
        run: uv run --locked python scripts/test-full.py --profile full
      - name: Clippy is warning-free
        run: cargo clippy --all-targets --locked -- -D warnings
